# Generated by Django 5.0.1 on 2024-01-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_pic',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
